#!/bin/sh

# Generic bootstrap file. 
# If this fails for you, check for a bootstrap file for your platform.

set -x
aclocal
libtoolize
autoheader
automake --gnu --add-missing
autoconf
./configure "$@"
