# include/Makefile 
#
# RTV
# $Id: Makefile,v 1.2 2001-07-04 01:31:23 gerkey Exp $
###########################################################################

clean:
	rm -f *~ playerIO.*

# DO NOT DELETE


