#!/bin/bash

echo "Starting Stage..."
stage -o darpatech.world &
sleep 5

echo "Starting Clients..."


# A PUCK-COLLECTOR
echo "Forager"
forage -p 6801 &

# RUN JOYSTICK AND PLAYERV ON THE SAME ROBOT
echo "Joystick"
joystick -p 6800 & 

echo "Viewer" 
playerv '-p' 6800 --laser:0 --lbd:0 --position:0 &

# 50 PHEROBOTS
echo "Pherobots"
./many pherobot 6665 6714 &


echo "done".
